spring.application.name=week2
app.mail.host=localhost
app.mail.port=25
app.mail.from=welcome@demo.com
app.notification.pool-size=1
app.notification.retry-delay=2s
app.notification.enabled=false
spring.datasource.url=jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true 
spring.jpa.open-in-view=true 
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.generate_statistics=true

spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

